site_name: "React 中文文档"
site_author: Mingmin Yu
site_description: >-
  React 中文文档
site_url: "https://mingminyu.github.io"

copyright: Copyright &copy; 2024, Mingmin Yu

theme:
  name: material
  # custom_dir: overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.tabs.link
    - content.footnote.tooltips
    - navigation.instant
    - navigation.instant.progress
    # - navigation.instant.prefetch
    # - navigation.prune
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    # - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 暗黑模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 明亮模式
  
  favicon: custom/assets/react.svg
  logo: custom/assets/react.svg
  language: zh

plugins:
  - blog:
      blog_toc: true
      post_date_format: short
      post_url_date_format: yyyy/MM/dd
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_excerpt_max_authors: 2
      archive_toc: true
      categories_toc: true
      categories_slugify_separator: _
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      pagination_format: "~2~"
      pagination_if_single_page: false
      pagination_keep_content: true

  - tags
  - search
  - toggle-sidebar
  - tags:
      enabled: true

extra:
  generator: false
  social:
    - icon: fontawesome/solid/book
      link: https://cn.vuejs.org/guide/introduction.html

markdown_extensions:
  - abbr
  - tables
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 教程:
    - 快速入门: 
      - index.md
      - 井字棋: quickstart/tic-tac-toe.md
      - React 哲学: quickstart/thinking-in-react.md
    - 安装:
      - installation/index.md
      - 启动一个新的 React 项目: installation/start-a-new-react-project.md
      - 将 React 添加到现有项目中: installation/add-react-to-an-existing-project.md
      - 使用 TypeScript: installation/use-typescript.md
    
    - 描述 UI:
      - describing-ui/index.md
      - 你的第一个组件: describing-ui/your-first-component.md
      - 组件的导入与导出: describing-ui/importing-and-exporting-components.md
      - 使用 JSX 书写标签语言: describing-ui/writing-markup-with-jsx.md
      - 在 JSX 中通过大括号使用 JavaScript: describing-ui/javascript-in-jsx-with-curly-braces.md
      - 将 Props 传递给组件: describing-ui/passing-props-to-a-component.md
      - 条件渲染: describing-ui/conditional-rendering.md
      - 渲染列表: describing-ui/rendering-lists.md
      - 保持组件纯粹: describing-ui/keeping-components-pure.md
